version: "3"
services:
 csvserver:
  image: infracloudio/csvserver:latest
  ports:
    - "9393:9300"
  volumes:
    - "$PWD/inputFile:/csvserver/inputdata"
  environment:
      - CSVSERVER_BORDER=Orange
  restart: unless-stopped
